name: Cloudflare

on:
    schedule:
        - cron: "*/15 * * * *"
    workflow_dispatch:

permissions:
    issues: write
    contents: read

jobs:
    Cloudflare:
        runs-on: ubuntu-latest
        steps:
            - uses: guilhem/rss-issues-action@0.5.2
              continue-on-error: true
              with:
                  repo-token: ${{ secrets.GITHUB_TOKEN }}
                  feed: "https://www.cloudflarestatus.com/history.atom"
                  prefix: "[Cloudflare]"
                  dry-run: "false"
                  lastTime: "24h"
                  labels: "Cloudflare"
