name: Generate Index Feed

on:
    schedule:
        - cron: "0 7,14 * * *"
    workflow_dispatch: # Allow manual triggering

permissions:
    contents: write
    issues: read

jobs:
    generate-rss:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.10"

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install requests feedgenerator pytz

            - name: Generate RSS feed
              run: python _python/feed-generator.py
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  REPO_OWNER: SecOpsNews
                  REPO_NAME: News
                  OUTPUT_FILE: index.md

            - name: Commit and push
              run: |-
                  git diff
                  git config user.name "GitHub Action"
                  git config user.email "action@github.com"
                  git diff --quiet || (git add -A && git commit -m "New Feed")
                  git push
