---
name: RSS Aws

on:
    schedule:
        # “At every 30th minute past every hour from 8 through 19
        # on Monday, Tuesday, Wednesday, Thursday, and Friday.”
        # - cron: "*/30 * * * *"
    workflow_dispatch:

permissions:
    issues: write
    contents: read

jobs:
    api_gateway_eu-west-1:
        runs-on: ubuntu-latest
        steps:
            - uses: guilhem/rss-issues-action@0.5.2
              continue-on-error: true
              with:
                  repo-token: ${{ secrets.GITHUB_TOKEN }}
                  feed: "https://status.aws.amazon.com/rss/apigateway-eu-west-1.rss"
                  prefix: "[AWS]"
                  dry-run: "false"
                  lastTime: "24h"
                  labels: "apigateway, eu-west-1"

    cloudwatch_eu-west-1:
        runs-on: ubuntu-latest
        steps:
            - uses: guilhem/rss-issues-action@0.5.2
              continue-on-error: true
              with:
                  repo-token: ${{ secrets.GITHUB_TOKEN }}
                  feed: "https://status.aws.amazon.com/rss/cloudwatch-eu-west-1.rss"
                  prefix: "[AWS]"
                  dry-run: "false"
                  lastTime: "24h"
                  labels: "cloudwatch, eu-west-1"

    dynamodb_eu-west-1:
        runs-on: ubuntu-latest
        steps:
            - uses: guilhem/rss-issues-action@0.5.2
              continue-on-error: true
              with:
                  repo-token: ${{ secrets.GITHUB_TOKEN }}
                  feed: "https://status.aws.amazon.com/rss/dynamodb-eu-west-1.rss"
                  prefix: "[AWS]"
                  dry-run: "false"
                  lastTime: "24h"
                  labels: "dynamodb, eu-west-1"

    ecr_eu-west-1:
        runs-on: ubuntu-latest
        steps:
            - uses: guilhem/rss-issues-action@0.5.2
              continue-on-error: true
              with:
                  repo-token: ${{ secrets.GITHUB_TOKEN }}
                  feed: "https://status.aws.amazon.com/rss/ecr-eu-west-1.rss"
                  prefix: "[AWS]"
                  dry-run: "false"
                  lastTime: "24h"
                  labels: "ecr, eu-west-1"

    eks_eu-west-1:
        runs-on: ubuntu-latest
        steps:
            - uses: guilhem/rss-issues-action@0.5.2
              continue-on-error: true
              with:
                  repo-token: ${{ secrets.GITHUB_TOKEN }}
                  feed: "https://status.aws.amazon.com/rss/eks-eu-west-1.rss"
                  prefix: "[AWS]"
                  dry-run: "false"
                  lastTime: "24h"
                  labels: "eks, eu-west-1"

    eventbridge_eu-west-1:
        runs-on: ubuntu-latest
        steps:
            - uses: guilhem/rss-issues-action@0.5.2
              continue-on-error: true
              with:
                  repo-token: ${{ secrets.GITHUB_TOKEN }}
                  feed: "https://status.aws.amazon.com/rss/events-eu-west-1.rss"
                  prefix: "[AWS]"
                  dry-run: "false"
                  lastTime: "24h"
                  labels: "eventbridge, eu-west-1"

    guardduty_eu-west-1:
        runs-on: ubuntu-latest
        steps:
            - uses: guilhem/rss-issues-action@0.5.2
              continue-on-error: true
              with:
                  repo-token: ${{ secrets.GITHUB_TOKEN }}
                  feed: "https://status.aws.amazon.com/rss/guardduty-eu-west-1.rss"
                  prefix: "[AWS]"
                  dry-run: "false"
                  lastTime: "24h"
                  labels: "guardduty, eu-west-1"

    sns_eu-west-1:
        runs-on: ubuntu-latest
        steps:
            - uses: guilhem/rss-issues-action@0.5.2
              continue-on-error: true
              with:
                  repo-token: ${{ secrets.GITHUB_TOKEN }}
                  feed: "https://status.aws.amazon.com/rss/sns-eu-west-1.rss"
                  prefix: "[AWS]"
                  dry-run: "false"
                  lastTime: "24h"
                  labels: "sns, eu-west-1"

    sqs_eu-west-1:
        runs-on: ubuntu-latest
        steps:
            - uses: guilhem/rss-issues-action@0.5.2
              continue-on-error: true
              with:
                  repo-token: ${{ secrets.GITHUB_TOKEN }}
                  feed: "https://status.aws.amazon.com/rss/sqs-eu-west-1.rss"
                  prefix: "[AWS]"
                  dry-run: "false"
                  lastTime: "24h"
                  labels: "sqs, eu-west-1"

    s3_eu-west-1:
        runs-on: ubuntu-latest
        steps:
            - uses: guilhem/rss-issues-action@0.5.2
              continue-on-error: true
              with:
                  repo-token: ${{ secrets.GITHUB_TOKEN }}
                  feed: "https://status.aws.amazon.com/rss/s3-eu-west-1.rss"
                  prefix: "[AWS]"
                  dry-run: "false"
                  lastTime: "24h"
                  labels: "s3, eu-west-1"

    vpc_eu-west-1:
        runs-on: ubuntu-latest
        steps:
            - uses: guilhem/rss-issues-action@0.5.2
              continue-on-error: true
              with:
                  repo-token: ${{ secrets.GITHUB_TOKEN }}
                  feed: "https://status.aws.amazon.com/rss/vpc-eu-west-1.rss"
                  prefix: "[AWS]"
                  dry-run: "false"
                  lastTime: "24h"
                  labels: "vpc, eu-west-1"

    certificates_eu-west-1:
        runs-on: ubuntu-latest
        steps:
            - uses: guilhem/rss-issues-action@0.5.2
              continue-on-error: true
              with:
                  repo-token: ${{ secrets.GITHUB_TOKEN }}
                  feed: "https://status.aws.amazon.com/rss/certificatemanager-eu-west-1.rss"
                  prefix: "[AWS]"
                  dry-run: "false"
                  lastTime: "24h"
                  labels: "certificates, eu-west-1"

    cloudformation_eu-west-1:
        runs-on: ubuntu-latest
        steps:
            - uses: guilhem/rss-issues-action@0.5.2
              continue-on-error: true
              with:
                  repo-token: ${{ secrets.GITHUB_TOKEN }}
                  feed: "https://status.aws.amazon.com/rss/cloudformation-eu-west-1.rss"
                  prefix: "[AWS]"
                  dry-run: "false"
                  lastTime: "24h"
                  labels: "cloudformation, eu-west-1"

    cloudtrail_eu-west-1:
        runs-on: ubuntu-latest
        steps:
            - uses: guilhem/rss-issues-action@0.5.2
              continue-on-error: true
              with:
                  repo-token: ${{ secrets.GITHUB_TOKEN }}
                  feed: "https://status.aws.amazon.com/rss/cloudtrail-eu-west-1.rss"
                  prefix: "[AWS]"
                  dry-run: "false"
                  lastTime: "24h"
                  labels: "cloudtrail, eu-west-1"

    lambda_eu-west-1:
        runs-on: ubuntu-latest
        steps:
            - uses: guilhem/rss-issues-action@0.5.2
              continue-on-error: true
              with:
                  repo-token: ${{ secrets.GITHUB_TOKEN }}
                  feed: "https://status.aws.amazon.com/rss/lambda-eu-west-1.rss"
                  prefix: "[AWS]"
                  dry-run: "false"
                  lastTime: "24h"
                  labels: "lambda, eu-west-1"

    secrets_eu-west-1:
        runs-on: ubuntu-latest
        steps:
            - uses: guilhem/rss-issues-action@0.5.2
              continue-on-error: true
              with:
                  repo-token: ${{ secrets.GITHUB_TOKEN }}
                  feed: "https://status.aws.amazon.com/rss/secretsmanager-eu-west-1.rss"
                  prefix: "[AWS]"
                  dry-run: "false"
                  lastTime: "24h"
                  labels: "secrets, eu-west-1"

    image_builder_eu-west-1:
        runs-on: ubuntu-latest
        steps:
            - uses: guilhem/rss-issues-action@0.5.2
              continue-on-error: true
              with:
                  repo-token: ${{ secrets.GITHUB_TOKEN }}
                  feed: "https://status.aws.amazon.com/rss/imagebuilder-eu-west-1.rss"
                  prefix: "[AWS]"
                  dry-run: "false"
                  lastTime: "24h"
                  labels: "image_builder, eu-west-1"

    route53_eu-west-1:
        runs-on: ubuntu-latest
        steps:
            - uses: guilhem/rss-issues-action@0.5.2
              continue-on-error: true
              with:
                  repo-token: ${{ secrets.GITHUB_TOKEN }}
                  feed: "https://status.aws.amazon.com/rss/route53privatedns-eu-west-1.rss"
                  prefix: "[AWS]"
                  dry-run: "false"
                  lastTime: "24h"
                  labels: "route53, eu-west-1"

    resource_groups_eu-west-1:
        runs-on: ubuntu-latest
        steps:
            - uses: guilhem/rss-issues-action@0.5.2
              continue-on-error: true
              with:
                  repo-token: ${{ secrets.GITHUB_TOKEN }}
                  feed: "https://status.aws.amazon.com/rss/resourcegroupstaggingapi-eu-west-1.rss"
                  prefix: "[AWS]"
                  dry-run: "false"
                  lastTime: "24h"
                  labels: "resource_groups, eu-west-1"
